const factss = [
{id:1,
img:'https://images4.alphacoders.com/102/thumb-1920-102204.jpg',
def:"World's highest waterfall",
name:'Angel Falls, Venezuela',
},
{id:2,
img:'https://external-preview.redd.it/Wgqn7sAXY8dxZvJFgHRXhR7996o-_PTVZXXTwh75IjQ.jpg?auto=webp&s=58d16d921782edd163c0d61652398f78b1c1afda',
def:"Driest place on Earth",
name:'Atacama Desert, Chile',
},
{id:3,
img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhF6xPW-Nrv2rWijN4iDmlz-JfnpnG0qaBg&usqp=CAU',
def:"World's largest river basin",
name:' Amazon Basin, Brazil',
},
{id:4,
img:'https://c4.wallpaperflare.com/wallpaper/764/652/838/vitoria-regia-water-lily-at-pantanal-matogrossense-brazil-wallpaper-preview.jpg',
def:"World's largest tropical wetland",
name:'Pantanal, Brazil',
},
{id:5,
img:'https://www.chimuadventures.com/blog/wp-content/uploads/2017/02/shutterstock_389559904-e1582606125158.jpg',
def:"World's longest mountain ranges",
name:'Andes Ranges, South America',
},
{id:6,
img:'https://f.vividscreen.info/soft/85c2ca497f85cf42d94c5c2a56fa2190/Perito-Moreno-Glacier-wide-i.jpg',
def:"World's most beautiful glacier",
name:'Perito Moreno Glacier, Argentina',
},
{id:7,
img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1jofelAbqIgaxeXMzEmYRcyimvwQ8QjnaZA&usqp=CAU',
def:"World's most beautiful river",
name:'Cano Cristales, Colombia',
},
{id:8,
img:'https://img.theculturetrip.com/450x/smart/wp-content/uploads/2017/09/1024px-brazilian_amazon_rainforest.jpg',
def:"World's largest rainforest",
name:'Amazon Rainforest, Brazil',
},
{id:9,
img:'https://i.redd.it/8mau3irc42551.png',
def:"World's most beautiful oasis",
name:'Huacachina, Peru',
},
{id:10,
img:'https://pbs.twimg.com/media/C6_tkIGW0AAYcEc.jpg',
def:"World's largest salt flat",
name:'Salar de Uyuni, Bolivia',
},
{id:11,
img:'https://c4.wallpaperflare.com/wallpaper/160/433/261/iguazu-falls-at-sunrise-state-of-parana-brazil-wallpaper-preview.jpg',
def:"World's largest waterfall system",
name:'Iguazu Falls, Argentina',
},
{id:12,
img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA_5H8ZbMxQRsV5X40b9cQhmb5wqU8svMKMt_VDFURLiKrADOlMkJf1Y9ZJWeXPLIH_sA&usqp=CAU',
def:"World's largest river by volume",
name:'Amazon River, Brazil',
},
{id:13,
img:'https://www.treehugger.com/thmb/4HiJtEyWgoSEyRboo6B1yUYmWrY=/720x540/smart/filters:no_upscale()/__opt__aboutcom__coeus__resources__content_migration__treehugger__images__2018__04__boiling-river-4-c25f93807c894d569655ce5362def21e.jpg',
def:"World's only boiling river",
name:'Shanay Timpishka, Peru',
},
{id:14,
img:'http://4.bp.blogspot.com/-_0cWhs6j-yk/VXUh5AnqvfI/AAAAAAAAzCg/vnUwOI02Q2g/s1600/venezuela-simas-Sima-Humboldt-earth-wonder-fun-facts-lifepopper-intrigue-2.jpg',
def:"World's largest sandstone sinkhole",
name:'Sima Humboldt, Venezuela',
},
{id:15,
img:'https://i.imgur.com/kxrvFiW.jpg',
def:"World's highest annual lightning",
name:'Catatumbo, Venezuela',
},
{id:16,
img:'https://c4.wallpaperflare.com/wallpaper/357/645/211/easter-island-chile-starry-night-statue-wallpaper-preview.jpg',
def:"World’s most secluded inhabited island",
name:'Easter Island, Chile',
},
{id:17,
img:'https://wallpaperaccess.com/full/6143677.jpg',
def:"World's largest Art Deco-style sculpture",
name:'Christ the Redeemer, Brazil',
},
{id:18,
img:'https://w0.peakpx.com/wallpaper/187/250/HD-wallpaper-kaieteur-falls-on-potaro-river-guyana-nature-water-green-falls.jpg',
def:"World's largest single drop waterfall",
name:'Kaieteur Falls, Guyana',
},
]
export default factss