const factss = [
{id:1,
img:'https://upload.travelawaits.com/ta/uploads/2021/04/2d81b379b17d288410d70a2d7b4ab2d81b3-800x800.jpg',
def:"World's highest waterfall",
name:'Angel Falls, Venezuela',
},
{id:2,
img:'https://external-preview.redd.it/Wgqn7sAXY8dxZvJFgHRXhR7996o-_PTVZXXTwh75IjQ.jpg?auto=webp&s=58d16d921782edd163c0d61652398f78b1c1afda',
def:"Driest place on Earth",
name:'Atacama Desert, Chile',
},
{id:3,
img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhF6xPW-Nrv2rWijN4iDmlz-JfnpnG0qaBg&usqp=CAU',
def:"World's largest river basin",
name:' Amazon Basin, Brazil',
},
{id:4,
img:'https://deih43ym53wif.cloudfront.net/pantanal-brazil_c73b8c6554.jpeg',
def:"World's largest tropical wetland",
name:'Pantanal, Brazil',
},
{id:5,
img:'https://www.chimuadventures.com/blog/wp-content/uploads/2017/02/shutterstock_389559904-e1582606125158.jpg',
def:"World's longest mountain ranges",
name:'Andes Ranges, South America',
},
{id:6,
img:'https://media.istockphoto.com/photos/sunset-at-perito-moreno-glacier-picture-id504752312?k=20&m=504752312&s=170667a&w=0&h=RrEMzImxm4PcrYoZGMCRo60oABSGkEbgtr9Bj6BWfvc=',
def:"World's most beautiful glacier",
name:'Perito Moreno Glacier, Argentina',
},
{id:7,
img:'https://traveliyow.files.wordpress.com/2020/09/cano_cristales4.jpg',
def:"World's most beautiful river",
name:'Cano Cristales, Colombia',
},
{id:8,
img:'https://img.theculturetrip.com/450x/smart/wp-content/uploads/2017/09/1024px-brazilian_amazon_rainforest.jpg',
def:"World's largest rainforest",
name:'Amazon Rainforest, Brazil',
},
{id:9,
img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA_5H8ZbMxQRsV5X40b9cQhmb5wqU8svMKMt_VDFURLiKrADOlMkJf1Y9ZJWeXPLIH_sA&usqp=CAU',
def:"World's largest river by volume",
name:'Amazon River, Brazil',
},
{id:10,
img:'https://pbs.twimg.com/media/C6_tkIGW0AAYcEc.jpg',
def:"World's largest salt flat",
name:'Salar de Uyuni, Bolivia',
},
{id:11,
img:'https://www.freewalldownload.com/natural-waterfalls-images/iguazu-falls-in-argentina-wallpapers-hd-pic-download.jpg',
def:"World's largest waterfall system",
name:'Iguazu Falls, Argentina',
},
{id:12,
img:'https://media.istockphoto.com/photos/atacama-desert-oasis-of-huacachina-peru-picture-id523790233?k=20&m=523790233&s=612x612&w=0&h=-r671XZGartQSZSkofHgNiCf5reo0goWEoZZkK6Nb0A=',
def:"World's most beautiful oasis",
name:'Huacachina, Peru',
},
{id:13,
img:'https://knowinsiders.com/stores/news_dataimages/dunglt/112020/13/00/0609_HistoryofSiteHEROIMAGE.jpg?rt=20201113001045',
def:"World's only boiling river",
name:'Shanay Timpishka, Peru',
},
{id:14,
img:'http://4.bp.blogspot.com/-_0cWhs6j-yk/VXUh5AnqvfI/AAAAAAAAzCg/vnUwOI02Q2g/s1600/venezuela-simas-Sima-Humboldt-earth-wonder-fun-facts-lifepopper-intrigue-2.jpg',
def:"World's largest sandstone sinkhole",
name:'Sima Humboldt, Venezuela',
},
{id:15,
img:'https://p4.wallpaperbetter.com/wallpaper/826/0/49/clouds-lightning-nature-rain-wallpaper-preview.jpg',
def:"World's highest annual lightning",
name:'Catatumbo, Venezuela',
},
{id:16,
img:'https://wallup.net/wp-content/uploads/2016/03/10/332858-enigma-nature-landscape-Moai-sculpture-starry_night-grass-moonlight-Easter_Island-Rapa_Nui-Chile-statue-stone-long_exposure-748x468.jpg',
def:"World’s most secluded inhabited island",
name:'Easter Island, Chile',
},
{id:17,
img:'https://images.pexels.com/photos/2818895/pexels-photo-2818895.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
def:"World's largest Art Deco-style sculpture",
name:'Christ the Redeemer, Brazil',
},
{id:18,
img:'https://www.wondermondo.com/wp-content/uploads/2017/10/Kaieteur.jpg',
def:"World's largest single drop waterfall",
name:'Kaieteur Falls, Guyana',
},
]
export default factss