export default [
  //no need name for array
  {
    id: 1,
    name: 'Salar de Uyuni',
    country: 'Bolivia',
    image: 'https://wallpapercave.com/wp/wp4202139.jpg',
    data: 'Salar de Uyuni is the largest salt flat in  the world containing more than 10 billion tonnes of salt but, what makes this place so unique is the mirror effect caused after a rainfall, which fades away the limits between the sky and the land, making it look as if you were walking on the clouds.This salt flat is an endless criss-cross of hexagonal lines caused by the crystalline nature of salt.That’s not all, in the middle of this great salt desert is a hotel made entirely out of salt! Constructed using salt bricks and mortar, everything inside the hotel, including the chairs, tables and beds are all made of salt.',
    info: 'This video pretty much covers the paradise in Bolivia!',
    iframes: 'https://www.youtube.com/embed/1vPMD3wmaZo',
  },
  {
    id: 2,
    name: 'Iguazu Falls',
    country: 'Argentina',
    image: 'https://www.freewalldownload.com/natural-waterfalls-images/iguazu-falls-in-argentina-wallpapers-hd-pic-download.jpg',
    data: " Voted as one of the seven wonders of nature and considered the most beautiful waterfall in the world, Iguazu Falls is located in the border between Argentina, Paraguay and  Brazil.It is 1.7 miles wide and comprises of not 1 but 275 waterfalls!!The Devil's throat is the leading attraction consisting of 14 waterfalls in total and is shaped like a horseshoe. Together, they make up the  most surreal and largest waterfall system in the world.                                                                                                                                                                                               ",
    info: 'A glimpse into the unimaginable Iguazu Falls',
    iframes: 'https://www.youtube.com/embed/kY5G8s99Fl8',
  },
  {
    id: 3,
    name: 'Easter Island',
    country: 'Chile',
    image: 'https://wallup.net/wp-content/uploads/2016/03/10/332858-enigma-nature-landscape-Moai-sculpture-starry_night-grass-moonlight-Easter_Island-Rapa_Nui-Chile-statue-stone-long_exposure-748x468.jpg',
    data: 'Easter Islands also known as Rapa Nui is one of the most secluded  islands in the world. The island is most famous for its nearly 1,000 extant monumental statues, called moai, which were created by the early Rapa Nui people.The bodies of these stone sculptures are buried underneath the ground with only the face and shoulders above the ground facing the island to symbolize protection. There is also an astounding historic film about this island called Rapa Nui.',
    info: 'The incredible story of Rapa Nui in short!',
    iframes: 'https://www.youtube.com/embed/fwwpSypNPro',
  },
  {
    id: 4,
    name: 'Catatumbo River',
    country: 'Venezuela',
    image: 'https://p4.wallpaperbetter.com/wallpaper/826/0/49/clouds-lightning-nature-rain-wallpaper-preview.jpg',
    data: 'Catatumbo is the most electric place on Earth. This is where the Catatumbo lightning occurs, an atmospheric phenomenon that occurs over the mouth of the Catatumbo River where it empties into Lake Maracaibo in Venezuela. It originates from a mass of storm clouds at an altitude of more than 1 km, and occurs during 140 to 160 nights a year, nine hours per day, and from 16 to 40 times per minute.This is the most craziest phenomenon and yet not many people know about it.',
    info: "A must watch to believe what's happening! ",
    iframes: 'https://www.youtube.com/embed/4DH8LAa-caA',
  },
  {
    id: 5,
    name: 'Machu Picchu',
    country: 'Peru',
    image: 'https://cdn.kimkim.com/files/a/content_articles/featured_photos/2135c94551edd571a3096098a1c87af5c81eebeb/big-9d50e02291c74efc2260c03d491f4ac4.jpg',
    data: 'More than 7,000 feet above sea level in the Andes Mountains, Machu Picchu is the most visited tourist destination in Peru. A symbol of the Incan Empire and built around 1450 AD, Machu Picchu was designated a UNESCO World Heritage Site in 1983 and was named one of the New Seven Wonders of the World in 2007.                                                                                                                                                                                                                                                                                           ',
    info: 'Do checkout this iconic video for more details!',
    iframes: 'https://www.youtube.com/embed/lNIEZ61PyG0',
  },
  {
    id: 6,
    name: 'El Pailon del Diablo',
    country: 'Ecuador',
    image: 'https://i.pinimg.com/originals/cd/5c/0f/cd5c0f28607b61185e4dc2b5cf35c9f5.jpg',
    data: "El Pailon Del Diablo  also known as Devil's Cauldron is a natural wonder made up of 3 waterfalls, found in Ecuador. Known for its emerald-green forest and diverse wildlife, 'The Cauldron' is a great spectacle and creates a powerful symphony of sound. For the best view, visitors must climb the steep path up and cross the suspension bridge which makes the trip even more worth it.",
    info: 'This video gives a small glimpse of the astonishing falls!',
    iframes: 'https://www.youtube.com/embed/3at0kkSR4Qc',
  },
  {
    id: 7,
    name: 'Christ the Redeemer',
    country: 'Brazil',
    image: 'https://images.pexels.com/photos/2818895/pexels-photo-2818895.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
    data: 'Christ the Redeemer is the largest art deco statue in the world. It is a colossal statue of Jesus Christ at the summit of Mount Corcovado.A symbol of Christianity across the world, the statue has also become a cultural icon of both Rio de Janeiro and Brazil, and is listed as one of the New 7 wonders of the world.',
    info: 'Check out the brief history of this incredible statue',
    iframes: 'https://www.youtube.com/embed/jGFZfqTymEg',
  },
  {
    id: 8,
    name: 'Cano Crystal river',
    country: 'Colombia',
    image: 'https://traveliyow.files.wordpress.com/2020/09/cano_cristales4.jpg',
    data: 'Also known as the River of Five Colors, Cano Cristales is the most spectacular natural wonder in the country. Found in the mountain range of Serranía de la Macarena, the river mesmerizes with amazing colors: vivacious yellow, green, blue, black and red shades quiver from the bottom.The Liquid Rainbow is caused by a unique phenomena: a red plant – Macarenia clavigera – growing in the riverbed. Other colors come from black rocks, green algae, blue water and yellow sand, producing an iridescent effect. Cano Cristales is regarded as the most beautiful river in the world.',
    info: 'This short video gives a peek into the beautiful river',
    iframes: 'https://www.youtube.com/embed/eF7rtii_qJM',
  },
  {
    id: 9,
    name: 'Shanay Timpishka',
    country: 'Peru',
    image: 'https://knowinsiders.com/stores/news_dataimages/dunglt/112020/13/00/0609_HistoryofSiteHEROIMAGE.jpg?rt=20201113001045',
    data: 'The Shanay-Timpishka, also known as La Bomba, is a tributary of the Amazon River, is the only boiling river in the world. It is 6.4 km long and is known for the very high temperature of its waters—from 45 °C  to nearly 100 °C. This very high degree of heat is sufficient to kill any form of life, including humans, in a mere few minutes.',
    info: 'check-out this remarkable video to believe the impossible!',
    iframes: 'https://www.youtube.com/embed/yRNwHoc7bq0',
  },
  {
    id: 10,
    name: 'Angel Falls',
    country: 'Venezuela',
    image: 'https://upload.travelawaits.com/ta/uploads/2021/04/2d81b379b17d288410d70a2d7b4ab2d81b3-800x800.jpg',
    data: 'Angel Falls is the world’s highest uninterrupted waterfall. Located in Canaima National Park, the waterfall tumbles from a cleft near the summit of table top mountain Auyán-tepu into what is known as Devil’s Canyon, 3212 feet (979m) below. Considered among the world’s most dazzling natural wonders, Angel Falls are a truly unforgettable spectacle.',
    info: 'Have a near experience of this falls here!',
    iframes: 'https://www.youtube.com/embed/L_tqK4eqelA',
  },
  {
    id: 11,
    name: 'Kaieteur Falls',
    country: 'Guyana',
    image: 'https://www.wondermondo.com/wp-content/uploads/2017/10/Kaieteur.jpg',
    data: "Kaieteur Falls is the world's largest single drop waterfall by the volume of water flowing over it. Located on the Potaro River in the Kaieteur National Park, this gem sits in a section of the Amazon rainforest in a completely isolated place and can be toured by a helicopter or a plane.",
    info: 'check-out a small sight of this falls',
    iframes: 'https://www.youtube.com/embed/jKBb6RcVdxU',
  },
  {
    id: 12,
    name: 'Los Roques',
    country: 'Venezuela',
    image: 'https://emeraldwateranglers.com/wp-content/gallery/venezuela/LR.21.jpg',
    data: 'Los Roques is an archipelago off the northern coast of Venezuela with over 300 small islands, cays and sand banks that ring a central shallow lagoon. It was created in 1972 to protect the marine ecosystem of exceptional beauty and ecological value dominated by coral reefs, mangroves, and seagrass beds. It is without a doubt one of the most beautiful natural areas of Venezuela.',
    info: 'Do have a small glance of this archipelago',
    iframes: 'https://www.youtube.com/embed/yYbqJRA6beQ',
   },
  {
    id: 13,
    name: 'cordillera huayhuash',
    country: 'Peru',
    image: 'https://c4.wallpaperflare.com/wallpaper/591/243/641/peru-cordillera-huayhuash-mountains-valley-wallpaper-preview.jpg',
    data: ' The Cordillera Huayhuash is the site of the famous “Huayhuash Trek”, which is considered one of the best treks in the world.  The Cordillera Huayhuash trek has become well-known among outdoors enthusiasts for its sheer mountain peaks, pristine glacial lakes, Alpine trees  and encounters with traditional Andean culture.',
    info: 'Look into each fragment of the amazing Huayhuash trek here',
    iframes: 'https://www.youtube.com/embed/GoSXdc5FymI',
  },
  {
    id: 14,
    name: 'lencois maranhenses',
    country: 'Brazil',
    image: 'https://cdn.wallpapersafari.com/2/89/3MoWRq.jpg',
    data: 'The Lençóis Maranhenses National Park, located in Maranhão state in northeastern Brazil, is one of the  most marvellous and unique places in the world. An area encompassing about 1000 square kilometres of white silky sands intercepted at regular intervals by endless cool oases of turquoise lakes definitely deserves a visit.',
    info: 'Explore this stunning desert like landscape in this tiny video.',
    iframes: 'https://www.youtube.com/embed/Z24rvmd5cT8',
  },
  {
    id: 15,
    name: 'The Pantanal',
    country: 'Brazil',
    image: 'https://deih43ym53wif.cloudfront.net/pantanal-brazil_c73b8c6554.jpeg',
    data: "The Pantanal  is a natural region encompassing the world's largest tropical wetland area and the world's largest flooded grasslands.This massive wetland has the largest concentration of crocodiles in the world, with approximately 10 million caimans and definitely deserves a visit especially in the non- rainy season .",
    info: 'check-out this marvellous wetland here.',
    iframes: 'https://www.youtube.com/embed/U9X-eFRp2B4',
  },
  {
    id: 16,
    name: 'Pools of Millpu',
    country: 'Peru',
    image: 'https://www.wildandaway.com/wp-content/uploads/2019/10/How-To-Visit-The-Natural-Pools-of-Millpu-Ayacucho-Peru-3.jpg',
    data: 'The Natural Pools of Millpu (Aguas Turquesas Millpu/ Piscinas Naturales de Millpu) are 20 natural pools in the form of steps upon white stones, located in Ayacucho region of Peru at 3600 m above the sea level. What makes these lagoons so special is the color of water – turquoise or green depending on the season.',
    info: 'watch this short video to experience these stunning pools!',
    iframes: 'https://www.youtube.com/embed/btNiluceBdA',
  },
  {
    id: 17,
    name: 'Galapagos red beach',
    country: 'Ecuador',
    image: 'https://mybestplace.com/uploads/2020/07/Red-Sand-Beach-Galapagos-2.jpg',
    data: 'The beautiful red sand beach of Galapagos is located on the northern side of Rabida, a small volcanic island in the Galapagos archipelago located about 600 miles west of Ecuador. The intense red color of the sand is due to the high rate of iron present in the ashes of the nearby volcano and the corrosion of its slopes. It is known for its uncontaminated beauty and wild habitat populated by numerous colonies of sea lions and by a large variety of birds and rare endemic plant species.',
    info: 'Have a small glimpse of this island here.',
    iframes: 'https://www.youtube.com/embed/mXbWoyEYpwQ',
  },
  {
    id: 18,
    name: 'Marble Caves',
    country: 'Chile',
    image: 'https://motaen.com/upload/wallpapers/source/2015/08/09/18/05/45115/mota.ru-20150808089.jpg',
    data: "Chile's Marble Caves is one of the most extraordinary places to visit in South America. Over thousands of years, this mineral-rich glacier water changed the color and shape of the Marble Cave formations to beautiful hues of blues, greens, blacks, and yellows.They are a series of sculpted caves in the General Carrera Lake in the heart of Patagonia.",
    info: 'Look through all details of this notable caves here!',
    iframes: 'https://www.youtube.com/embed/EK1TEeGrrYk',
  },
  {
    id: 19,
    name: 'Three Sisters Falls',
    country: 'Peru',
    image: 'https://www.eatplayeasy.com/wp-content/uploads/2019/02/Waterfalls-6-Seven-Sisters-Waterfalls-1-1024x682.jpg',
    data: 'Three Sisters Falls/Tres Hermanas Falls is reportedly the third tallest waterfall in the world, with a height of 914 metres. The falls are named for the three most visible tiers, the three sisters. "Cataratas las Tres Hermanas" means "Waterfalls of the three sisters".',
    info: 'Take a quick view of these falls here!',
    iframes: 'https://www.youtube.com/embed/fVt2_X7fI0o',
  },
  {
    id: 20,
    name: 'Mount Roraima',
    country: 'Venezuela',
    image: 'https://www.gaia.com/wp-content/uploads/article-migration-image-Mount-Roraima.jpg',
    data: 'Mount Roraima is a spectacular flat table mountain surrounded by sheer cliffs creating an island floating in the sky on the plains of the Gran Sabana (The Great Savannah), a large part of south eastern Venezuela. The mountain is the highest of the Pakaraima chain of tepuis in South America. Covered with unique structures, animals and plants found nowhere else on earth this unique table top mountain is a paradise for the travellers.',
    info: 'Visit this striking video for a quick glance!',
    iframes: 'https://www.youtube.com/embed/aGv_MitUe7A',
  },
  {
    id: 21,
    name: 'Rainbow Mountains',
    country: 'Peru',
    image: 'https://i.pinimg.com/originals/99/43/c4/9943c4bee9489b1f93c6bd1a13b2826f.jpg',
    data: "One of the most magnificent geologic features in the world is the Rainbow Mountain of the Peruvian Andes. The mountain is striped with colors ranging from turquoise to lavender to maroon and gold.  While you’ll probably never make it to Oz, you can go to a land where you’ll be positively surrounded by color. Just take a trip down to the Rainbow Mountain in Peru.",
    info: 'Experience these stunning mountains here!',
    iframes: 'https://www.youtube.com/embed/gNfthVQGin4',
  },
  {
    id: 22,
    name: 'Moreno glacier',
    country: 'Argentina',
    image: 'https://media.istockphoto.com/photos/sunset-at-perito-moreno-glacier-picture-id504752312?k=20&m=504752312&s=170667a&w=0&h=RrEMzImxm4PcrYoZGMCRo60oABSGkEbgtr9Bj6BWfvc=',
    data: 'Perhaps the world’s most impressive glacier, Perito Moreno Glacier in Los Glaciares National Park is a must-see phenomenon and a highlight for many on a  trip to Argentina. Since its UNESCO inscription 40 years ago, watching the  blue ice break away from the glacier and plunge into the ice field below never seems to get old.',
    info: 'watch the ice collapsing in this amazing glacier here!',
    iframes: 'https://www.youtube.com/embed/JivQvX1jT-w',
  },
  {
    id: 23,
    name: 'Huacachina',
    country: 'Peru',
    image: 'https://media.istockphoto.com/photos/atacama-desert-oasis-of-huacachina-peru-picture-id523790233?k=20&m=523790233&s=612x612&w=0&h=-r671XZGartQSZSkofHgNiCf5reo0goWEoZZkK6Nb0A=',
    data: "Huacachina is a desert oasis and tiny village just west of the city of Ica in southwestern Peru. At its center are the green waters of the Huacachina Lagoon, ringed by palm trees and thought to have therapeutic properties. The lagoon's shores are also dotted with bars and clubs.",
    info: 'Look through this detailed video about this trip!',
    iframes: 'https://www.youtube.com/embed/1nFWm7RIAS8',
  },
  {
    id: 24,
    name: 'Fervedouro',
    country: 'Brazil',
    image: 'https://media-cdn.tripadvisor.com/media/photo-s/17/88/ce/ff/fervedouro.jpg',
    data: ' Nestled deep in the Jalapão State Park in central Brazil is a sight for sore eyes. Among the dense vegetation, the sweltering heat and too many banana plants to mention is a stunning blue oasis that’s perfect for an afternoon dip.The Fervedouro pool is crystal clear and sits on a bed of white sand, making it one of the most picturesque natural pools in the world.',
    info: 'check-out this comprehensive video!',
    iframes: 'https://www.youtube.com/embed/_ESNcAyBCOw',
  },
  {
    id: 25,
    name: 'Laguna Paron',
    country: 'Peru',
    image: 'https://i.pinimg.com/originals/fc/ee/8d/fcee8d03307350f18123e824ad5c5be6.jpg',
    data: 'Laguna Paron is the largest and most beautiful lake in Huascaran National Park and sits at 4,200 meters above sea level. The backdrop with Piramide de Garcilaso, the view to the massive Huandoy mountains, and glimpses of other snow-capped peaks is breathtaking. Laguna 69 Trail is a 8.6 mile moderately trafficked out and back trail located near Yanama, Peru that features a lake and is rated as moderate. The trail is primarily used for hiking, walking, nature trips, and bird watching and is accessible year-round.',
    info: 'visit this video to experience the surreal adventure',
    iframes: 'https://www.youtube.com/embed/_LhY_-zk3Ig',
  },
 ];
